name: Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!master'

jobs:
  windows:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'
      - name: Install Nuke
        run: dotnet tool install Nuke.GlobalTool --global
      - name: Make build script executable
        run: chmod +x ./.nuke/build.sh
      - name: Run Nuke Build
        run: ./.nuke/build.sh --GitHubToken ${{ secrets.GITHUB_TOKEN }}